using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Text.RegularExpressions;

namespace OpenHeroSelectGUI.Functions
{
    /// <summary>
    /// Alchemy related static resources
    /// </summary>
    public static partial class Alchemy
    {
        [GeneratedRegex(@"\S.*?(?=[^\S\n]*\|ig\w*Matrix\w*Select)")] // possibly ignore case
        private static partial Regex igSkinRX();

        private static string? Root;
        public static readonly string INI = Path.Combine(OHSpath.Temp, "OHSGUI_Alchemy.ini");
        public static string? Optimizer { get; private set; }

        static Alchemy() => _ = Reset();

        /// <summary>
        /// Attempts to locate sg<see cref="Optimizer"/>.exe based on the 'IG_ROOT' environment variable.
        /// </summary>
        /// <returns><see langword="True"/> if the optimizer executable could not be found or configured; otherwise, <see langword="false"/>.</returns>
        public static bool Reset()
        {
            Root = Environment.GetEnvironmentVariable("IG_ROOT");
            Optimizer = !string.IsNullOrWhiteSpace(Root)
                            && Path.Combine(Root, "bin", "sgOptimizer.exe") is string O
                            && File.Exists(O) ? O : null;
            return Optimizer is null;
        }
        /// <summary>
        /// Runs the optimizations of <see cref="INI"/> on the <paramref name="SourceIGB"/> file to "[OHS]/Temp/temp.igb", and reads the sgOptimizer output.
        /// </summary>
        /// <returns>The optimizer output, if optimized successfully and the output is not null or empty; otherwise <see langword="null"/>.</returns>
        public static string? RunOptTemp(string? SourceIGB)
        {
            string? Output = Util.RunDosCommnand(Optimizer!,
                $"\"{SourceIGB}\" \"{Path.Combine(OHSpath.Temp, "temp.igb")}\" \"{INI}\"");
            return !string.IsNullOrWhiteSpace(Output) ? Output : null;
        }
        /// <summary>
        /// Optimizes the <paramref name="SourceIGB"/> file to "[OHS]/Temp/temp.igb", using statistic optimizations, and reads the sgOptimizer output.
        /// </summary>
        /// <returns>The optimizer output, if optimized successfully; otherwise <see langword="null"/>.</returns>
        public static string? GetSkinStats(string? SourceIGB)
        {
            return File.Exists(SourceIGB) && Opt.Write(Opt.SkinInfo) ? RunOptTemp(SourceIGB) : null;
        }
        /// <summary>
        /// Optimizes the <paramref name="SourceIGB"/> file to "[OHS]/Temp/temp.igb", using skin statistic optimization, and gets igSkin from the sgOptimizer output.
        /// </summary>
        /// <returns>The igSkin name, if found and no exceptions happened; otherwise <see langword="null"/>.</returns>
        public static string? GetIntName(string? SourceIGB)
        {
            return File.Exists(SourceIGB) && Opt.Write(Opt.Combine([Opt.StatSkin]))
                && RunOptTemp(SourceIGB) is string Stats ? IntName(Stats) : null;
        }
        /// <summary>
        /// Searches for the igSkin name in skin <paramref name="Stats"/>, using regex.
        /// </summary>
        /// <returns>The igSkin name, if found; otherwise <see langword="null"/>.</returns>
        public static string? IntName(string Stats) => igSkinRX().Match(Stats) is Match M && M.Success ? M.Value : null;
        /// <summary>
        /// If Alchemy works, optimize <paramref name="SourceIGB"/>:
        /// Change igSkin from <paramref name="IntName"/> to <paramref name="Name"/>, add GlobalColor according to <paramref name="AlchemyCompatibility"/> and convert to Geo 2 if <paramref name="ConvGeo"/>.
        /// Write to <paramref name="TargetIGB"/>. Target folder must exist.
        /// </summary>
        /// <returns><see langword="True"/>, if optimized successfully; otherwise <see langword="false"/>.</returns>
        public static bool CopySkin(FileInfo SourceIGB, string TargetIGB, string Name, int AlchemyCompatibility, bool ConvGeo, string? igSkin = null, bool HexEdit = true)
        {
            return AlchemyCompatibility >= 8
                && Optimizer is not null
                && SourceIGB.Exists
                && Opt.Skins(Name, AlchemyCompatibility, ConvGeo, HexEdit, igSkin)
                && Util.RunExeInCmd(Optimizer, $"\"{SourceIGB}\" \"{TargetIGB}\" \"{INI}\"");
        }
    }
    /// <summary>
    /// Alchemy 5 optimizations for sgOptimizer.exe
    /// </summary>
    public static class Opt
    {
        public static readonly string Head = @"; Automatically generated by OpenHeroSelectGUI
[OPTIMIZE]
optimizationCount = {0}
hierarchyCheck = true";

        public static readonly string Stats = @"
separatorString = |
columnMaxWidth = -1
showColumnsMask = {0}
sortColumn = -1";

        public static readonly string StatTex = @"
name = igStatisticsTexture"
+ string.Format(Stats, "0x00000117") + Environment.NewLine
+ "useFullPath = false";

        public static readonly string StatGeo = @"
name = igStatisticsGeometry"
+ string.Format(Stats, "0x00500000");

        public static readonly string StatSkin = @"
name = igStatisticsSkin"
+ string.Format(Stats, "0x00000006");

        public static readonly string SkinInfo = string.Join(Environment.NewLine, Combine([StatSkin, StatTex, StatGeo]));

        public static readonly string CGA = @"
name = igConvertGeometryAttr
accessMode = 3
storeBoundingVolume = false";

        public static readonly string GGC = @"
name = igGenerateGlobalColor";

        public static readonly string Rename = @"
name = igChangeObjectName
objectTypeName = igNamedObject
targetName = {0}
newName = {1}";
        /// <summary>
        /// Create and write (if any) optimization set to change <paramref name="igSkin"/> to <paramref name="Name"/>, optimize according to <paramref name="AlchemyCompatibility"/>ibility and convert to Geo 2 if <paramref name="ConvGeo"/>.
        /// </summary>
        /// <returns><see langword="True" />, if any optimizations necessary or possible; otherwise <see langword="false"/>.</returns>
        public static bool Skins(string Name, int AlchemyCompatibility, bool ConvGeo, bool HexEdit, string? igSkin)
        {
            List<string> Optimizations = [];
            if (ConvGeo)  // convert to attr2
            {
                Optimizations.Add(CGA);
            }
            if (AlchemyCompatibility == 9)  // (there are issues sometimes if gc is already applied)
            {
                Optimizations.Add(GGC);
            }
            if (!(!HexEdit || string.IsNullOrWhiteSpace(igSkin) || igSkin == Name || igSkin.StartsWith("Bip01")))
            {
                Optimizations.Add(string.Format(Rename, igSkin, Name));
            }
            if (Optimizations.Count > 0)
            {
                return Write(Combine(Optimizations));
            }
            return false;
        }
        /// <summary>
        /// Tries to write the <paramref name="Opts"/> to <see cref="Alchemy.INI"/>, if Alchemy works.
        /// </summary>
        /// <returns><see langword="True"/>, if written successfully and Alchemy works; otherwise <see langword="false"/>.</returns>
        public static bool Write(string Opts)
        {
            if (Alchemy.Optimizer is null) { return false; }
            try { File.WriteAllText(Alchemy.INI, Opts); } catch { return false; }
            return true;
        }
        /// <summary>
        /// Tries to write the <paramref name="Opts"/> to <see cref="Alchemy.INI"/>, if Alchemy works.
        /// </summary>
        /// <returns><see langword="True"/>, if written successfully and Alchemy works; otherwise <see langword="false"/>.</returns>
        public static bool Write(IEnumerable<string> Opts)
        {
            if (Alchemy.Optimizer is null) { return false; }
            try { File.WriteAllLines(Alchemy.INI, Opts); } catch { return false; }
            return true;
        }
        /// <summary>
        /// Combine the <paramref name="Opts"/>, adding the optimization number/index and adding the <see cref="Head"/>er.
        /// </summary>
        /// <returns> The combined optimizations, incl. <see cref="Head"/>er, as <see cref="IEnumerable{T}"/>.</returns>
        public static IEnumerable<string> Combine(List<string> Opts) =>
            Opts.Select(static (o, i) => $"[OPTIMIZATION{i + 1}]{o}").Prepend(string.Format(Head, Opts.Count));
    }
}
